### PR TITLE
fix: upgrade traefik client library to support new resource packaging

### PR DESCRIPTION
**Pull request by mya-crabnebula**
## Motivation

As it stands, Switchboard cannot work with newer versions of Traefik as describe in gh-111. This change patches the project to include the newer version of the Traefik client library allowing it to operate with newer versions of traefik.

Resolves https://github.com/borchero/switchboard/issues/111

## Explanation

This change upgrades the Traefik client library, patches the various files that use the Traefik, and finally updates the ClusterRole defined in the helm chart to support watching the appropriate resources.

## Changes

- Patches go.mod
- Updates library usage
- Updates the kubernetes controller permissions.

## Checklist

- [x] I added relevant tests
- [x] I have updated the documentation if necessary

### CODE REVIEW

**Comment by Elegant996** [comment]
Yeah... This causes a problem because it forces everyone to switch to the new API. It's not really a fix in this case as it would quite literally break switchboard for everyone using the old API.

**Comment by borchero** [comment]
I will try working on this once the CI in this repo is fixed again (cf. #147). I can't replicate the failure locally, unfortunately, so this will likely take a bit of work.

**Comment by christian-vdz** [comment]
> Yeah... This causes a problem because it forces everyone to switch to the new API. It's not really a fix in this case as it would quite literally break switchboard for everyone using the old API.

Something has to be done, or switchboard will become unusable for all of us.
This should be release under a new major release (along with some dependency upgrades).

WYT?

**Comment by borchero** [comment]
I'd be very much in favor of updating. Unfortunately, I can't easily replicate the CI failure locally and I don't have too much time to look into this at the moment. @christian-vdz would you be able to investigate the failure? :pray: once that is fixed, I think that we can move rather fast to upgrade everything.

**Comment by christian-vdz** [comment]
> @christian-vdz would you be able to investigate the failure? 🙏 once that is fixed, I think that we can move rather fast to upgrade everything.

Yes I can take some time to try and fix it.  
Can you please allow workflows to run on this PR? https://github.com/borchero/switchboard/pull/159

**Comment by borchero** [comment]
Closing in favor of #159.

**Pull request closed without merging**
